name: Lint with Ruff

on:
  push:
    branches:
      - 'main'
  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
 
      - name: code checkout
      uses: actions/checkout@v2
 
     - uses: astral-sh/ruff-action@v3
     - run: ruff check
